### PR TITLE
Compat resource

### PR DESCRIPTION
**Pull request by damacus**
Using compat resource to use the new resource model. 
- [x] Reorder kitchen tests for easier testing
- [x] Tests work on TravisCI 
- [x] Automaster resource works
- [x] InSpec verifier

### CODE REVIEW

**Comment by richardlock** [comment]
Thanks Dan and Joel.  This is looking good.  I can move the tests over to InSpec in the morning if you like.  I noticed you've added a delayed service reload, which fixes one of the current issues.  On RHEL 7, the immediate service restart was causing systemd failures with several mount points in the same recipe due to multiple restarts.

**Comment by damacus** [comment]
Yeah that restart should only get called once. Which is the next problem
I'm trying to fix!

**Comment by richardlock** [comment]
I've fixed the issues with the resources and the various rubocop/foodcritic warnings, and added more comprehensive tests.  The Travis job is looking for the Gemfile - will it run without if the line is removed?  I haven't run test-kitchen with Ubuntu or RHEL 7, but these should work now.  I'll check tomorrow.

Upping the constraint on compat_resource got rid of some of the false warnings about properties with default=nil.

**Comment by damacus** [comment]
All test now pass on TravisCI and up in amazon with the latest CentOS 6 AMI. 

I'm omitting the driver name so it can be configured under `~/.kitchen/config.yml` .
Overrides for that central config are being set in this config file. 

For any images that have an annoying RequireTTY set (I'm looking at you CentOS and RHEL) I've set the test recipe to fix it. 

@richardlock  Do you also want these tested against RHEL7? 
I'll add that to the list and fix accordingly. 

Nice find on upgrading the compat_resource to fix those erroneous errors.

**Comment by richardlock** [comment]
Thanks Dan - good job on the requireTTY fix.  I'll retest.  With the renaming of the test cookbooks, would it be best to put the "_test" suffix back?  This seems to be a sensible pattern with cookbooks only required for test-kitchen to avoid namespace clashes and make clear they are only test fixtures.  Most of the Chef maintained cookbooks follow this pattern.

**Comment by damacus** [comment]
They're not name space clashing with anything that I can see at the moment.
But now you mention it, it can't harm.

Did you get these working with vagrant in the end?
The current vagrant version is borked by the looks of things

**Comment by damacus** [comment]
@richardlock that looks good to good know doesn't it?

**Comment by richardlock** [comment]
Yes, looks good now - thanks.  I had to use a .kitchen.local.yml to run tests in vagrant as it didn't have a driver specified, but it worked fine with centos 6.7/7.2 and ubuntu 16.04.

**Comment by damacus** [comment]
If you have settings in ~/.kitchen/config.yml it'll use those as defaults.

http://kitchen.ci/docs/getting-started/dynamic-configuration

**Pull request merged**
