### PR TITLE
24 - updates for chef 14

### LINKED ISSUE #24: map_entry resource does not work with Chef 14
The following recipe works just fine with Chef 12 and 13, but fails on Chef 14:

```
mapfile = '/etc/auto.mnt'

map_entry 'petalibrary' do
  user = node[cookbook_name]['automount']['remote_user']
  host = node[cookbook_name]['automount']['remote_host']
  dir = node[cookbook_name]['automount']['remote_dir']
  opts = node[cookbook_name]['automount']['opts']
  location ":sshfs\##{user}@#{host}:#{dir}"
  fstype 'fuse'
  options opts.join(',')
  map mapfile
end
```

```
       Converging 1 resources
       Recipe: cub_policy_lib_archivematica::default
         * map_entry[petalibrary] action create
           
           ================================================================================
           Error executing action `create` on resource 'map_entry[petalibrary]'
           ================================================================================
           
           NameError
           ---------
           undefined local variable or method `map' for #<#<Class:0x00000000049ab0d8>:0x00000000043ea810>
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/autofs/resources/map_entry.rb:12:in `block in class_from_file'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cub_policy_lib_archivematica/recipes/default.rb
           
            12: map_entry 'petalibrary' do
            13:   user = node[cookbook_name]['automount']['remote_user']
            14:   host = node[cookbook_name]['automount']['remote_host']
            15:   dir = node[cookbook_name]['automount']['remote_dir']
            16:   opts = node[cookbook_name]['automount']['opts']
            17:   location ":sshfs\##{user}@#{host}:#{dir}"
            18:   fstype 'fuse'
            19:   options opts.join(',')
            20:   map mapfile
            21: end
            22: 
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/cub_policy_lib_archivematica/recipes/default.rb:12:in `from_file'
           
           map_entry("petalibrary") do
             action [:create]
             default_guard_interpreter :default
             declared_type :map_entry
             cookbook_name "cub_policy_lib_archivematica"
             recipe_name "default"
             location ":sshfs#vagrant@testkitchen-cub-rh7.colorado.edu:/home/vagrant"
             fstype "fuse"
             options "_netdev,user,idmap=user,transform_symlinks,identityfile=/home/vagrant/.ssh/id_rsa,allow_other,default_permissions,uid=1000,gid=1000,umask=002,StrictHostKeyChecking=no"
             map "/etc/auto.mnt"
             key "petalibrary"
             mount_point "/mnt"
           end
           
           System Info:
           ------------
           chef_version=14.2.0
           platform=redhat
           platform_version=7.5
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
```

### PR DESCRIPTION
**Pull request by jayhendren**
Fixes #24 .

### CODE REVIEW

**Comment by jayhendren** [comment]
Not sure what's going on with the tests, looks like they never even got started:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

**Comment by bby-bishopclark** [comment]
This PR is a year old.  Wow!

FWIW, it applies cleanly on my hosts and fixes the problem.  And let's ignore that it took me this long to upgrade to what may become the last libre chef release.  :-D

(I recommend relaunching the test and I recommend approving this PR)

**Comment by richardlock** [comment]
Hi, sorry for the huge delay in merging this.  We are not using chef so much these days.

**Comment by bby-bishopclark** [comment]
Late is always better than never!  Thanks!

**Pull request merged**
