### PR TITLE
Support wildcard maps

### PR DESCRIPTION
**Pull request by jflemer-ndp**
- escape map names appropraitly to allow `*`
- improve robustness (regex matching)
- fixed a bug with the handling of fstype

### CODE REVIEW

**Comment by jflemer-ndp** [comment]
Resolved lint issues in #22. I'm not sure which is "better", but this passes your CI.

**Comment by richardlock** [comment]
kitchen test passes for all suites.

**Comment by jflemer-ndp** [comment]
@damacus would you mind tagging and releasing this to supermarket? Thanks!

**Comment by richardlock** [comment]
I've done that now @jflemer-ndp - sorry, I forgot to do it after merging earlier!

**Pull request merged**
